# Generated by Django 3.2.16 on 2023-02-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0005_auto_20230223_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('article_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
