# Generated by Django 3.2.16 on 2023-02-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='md5_checksum',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='sha256_checksum',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
