# Generated by Django 3.2.16 on 2023-02-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0002_auto_20230209_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_files', models.IntegerField()),
                ('max_filesize', models.IntegerField()),
                ('max_total_filesize', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.CharField(max_length=36),
        ),
    ]
