# Generated by Django 3.2.16 on 2023-02-12 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('demos', '0003_auto_20230212_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSummary',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='auth.user')),
                ('files', models.IntegerField()),
                ('size', models.IntegerField()),
            ],
        ),
    ]
